### ISSUE TITLE
Not all of the YARD text is showing up in the floating definition window

### ISSUE THREAD

**Issue by thornomad** [neoclide/coc-solargraph#10]
I'm new to coc.nvim and solargraph so forgive me if this is an obvious question. 

Assuming this reference code:

```
# Finds a person by email word word word word word word word word word word
# word word word word word word word word word word word word word word
# word word word word
# @return [Person]
def find_by_email(email)
  Person.where('LOWER(email)=?', email.strip.downcase).take
end
```
When I run `:call CocAction('doHover')` I end up seeing this:

![image](https://user-images.githubusercontent.com/124717/58883877-26751580-8694-11e9-9286-1c6115a486a9.png)

When the floating window appears during the completion selection I am getting more of the text, but still not all of it:

![image](https://user-images.githubusercontent.com/124717/58883933-44db1100-8694-11e9-94b2-90f5b7a4ee12.png)

_How do I get both of these windows to display the entire message ? Is this a solargraph issue or a coc-solargraph issue or a coc.nvim issue?

```
vim version: NVIM v0.4.0-dev
node version: v11.14.0
coc.nvim version: 0.0.68-1933fb7d51
term: iTerm.app
platform: darwin
```

**Comment by chemzqm** [comment]
upgrade coc.nvim, it's fixed.

**Comment by thornomad** [comment]
Thanks - yes!  Much better now!  What about the `&gt;` ?  Is that a problem on my end somewhere?  Appreciate it.
