### ISSUE TITLE
Issue with bundled solargraph

### ISSUE THREAD

**Issue by iovis** [neoclide/coc-solargraph#12]
Hi, I'm hoping someone can help me debug what could be going on in my system.

I was using Solargraph with COC and Bundler without issues for months:
```json
{
  "solargraph.useBundler": true,
}
```

And I have no idea what changed in my env, but now I get the following:
```
[coc.nvim] Solargraph failed to initialize.                                                                                                                                   
[coc.nvim] Failed to start Solargraph: /usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle (LoadError) 
from /usr/local/bin/bundle:23:in `<main>'                                                                                                                                   
```

Weird things to notice is this project is actually using ruby 2.5.1 and it's trying to use 2.6.0 for some reason —I use `rbenv`—. If I use the "global" solargraph, it works.

My `:checkhealth` looks fine:
```markdown
health#coc#check
========================================================================
  - OK: Environment check passed
  - OK: Javascript bundle found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
  - INFO: Host: /Users/david/.rbenv/shims/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v10.16.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```

Would someone know how to debug this?

**Comment by chemzqm** [comment]
Edit `/usr/local/bin/bundle` to see what ruby it's using, looks like you don't have solargraph installed for that ruby version.

**Comment by chemzqm** [comment]
You may have to use `solargraph.bundlerPath`

**Comment by Flink** [comment]
I actually have the opposite problem (but might be related), `solargraph` was working fine until today I’d say. Now I have this error: `[coc.nvim] Failed to start Solargraph: Error: [Bundler::GemNotFound] Could not find rake-12.3.2 in any of the sources`

I don’t try to start it through bundler, I even put `false` on the  "solargraph.useBundler" option but it still tries to start through bundler :thinking: Just did an upgrade of coc-solargraph but same result.

**Comment by Flink** [comment]
Just tried to downgrade solargraph, that’s a bug with the 0.34 version actually it seems.

**Comment by iovis** [comment]
> Just tried to downgrade solargraph, that’s a bug with the 0.34 version actually it seems.

Downgrading to 0.33.2 or 0.32.5 didn't seem to fix the issue for me.

> Edit /usr/local/bin/bundle to see what ruby it's using, looks like you don't have solargraph installed for that ruby version.

The problem is that for some reason it's now using `/usr/local/bin` instead of my `rbenv` path, but I don't really think it's because of this plugin.

Your `bundlerPath` suggestion worked, so I'll be using that from now on:
```json
{
  "solargraph.useBundler": true,
  "solargraph.bundlerPath": "/Users/david/.rbenv/shims/bundle"
}
```

Thank you very much!

**Comment by Flink** [comment]
Ok so your problem doesn’t seem to be related to mine in the end. Sorry for polluting your issue! :sweat_smile:

**Comment by iovis** [comment]
Every bit of help is useful, it could help other people that stumbles upon this from Google!

**Comment by AlanWarren** [comment]
Are you using zsh?

It seems to be the case, so just an FYI.  coc-solargraph uses solargraph-utils, which spawns an additional shell process.  It spawns zsh as a login shell, which bypasses your zshrc.  If you have rbenv sourced there, you'll need to move it into ~/.zprofile along with your PATH.  

More info. https://github.com/castwide/vscode-solargraph/issues/108#issuecomment-487359460

**Comment by iovis** [comment]
@AlanWarren Bingo!

I added the following to `~/.zprofile`:
```sh
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

And Solargraph doesn't complain anymore!

**Comment by chemzqm** [comment]
I don't like things like rbenv, it's confusing

**Comment by natematykiewicz** [comment]
@iovis I'm not even using rbenv and this helped me. Thank you!
