### ISSUE TITLE
Not showing symbols in xxx_spec.rb files

### ISSUE THREAD

**Issue by thornomad** [neoclide/coc-solargraph#13]
**How do I get the same suggestions I see when working on a file in my Rails project `app/` folder also in my `spec/` files?**

I am not sure if this is a con-solargraph configuration issue or a solargraph one ... 

Everything works great in my Rails project folder `app/`—however, I am not getting any of the Solargraph suggestions when I am in my `spec/` folder.

I tried removing it from `exclude:` in the configuration file but that didn't seem to do anything.  I'm sure I am missing something rather basic but cannot figure it out!

**Comment by chemzqm** [comment]
Need output from solargraph https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by thornomad** [comment]
HI - I turned on `verbose` setting and restarted vim ... this time just opening a single `spec/models/xxx_spec.rb` file to test it.

Right off the bat I noticed that: _when I open the `spec/` file directly it is not triggering Solargraph to even start ... I **don't** see this:_

<img width="260" alt="image" src="https://user-images.githubusercontent.com/124717/60515175-0e9bac00-9ca9-11e9-943f-871de0a83087.png">

Or this:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/124717/60515237-325ef200-9ca9-11e9-9553-08954923d72c.png">

There is no output to capture.  When I navigate to a `app/` or a `lib/` folder the server start is triggered.  But not in `spec/` ... 

is there a particular part of the verbose output that would help (the output from files in the `app/` folder is very long)?  

Might it have to do with a filetype setting (`ruby.spec` vs `ruby`) ?

**Comment by chemzqm** [comment]
it's problem of filetype

**Comment by thornomad** [comment]
How do I set it to include this filetype?  I did a quick search and [looking here](https://github.com/neoclide/coc-solargraph/blob/c6d620f39131c705ad81c50f8f3c1210514a3ea5/src/index.ts#L22) I thought maybe I could do a `solargraph.filetypes` config setting, but that didn't seem to work.  Here is what I tried:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/124717/60528620-ca1d0a00-9cc2-11e9-9fda-fb2845e5e56e.png">

**Comment by chemzqm** [comment]
Checkout `:h g:coc_filetype_map`

**Comment by thornomad** [comment]
Thank you!  That did it.
