### ISSUE TITLE
Not providing floating window arguments

### ISSUE THREAD

**Issue by sethen** [neoclide/coc-solargraph#15]
Autocompletion works fine, but when trying to receive the type hints for something like `[].assoc(` no floating window appears.  VSCode does not have this issue when Solargraph is installed as a plugin.

**Comment by sethen** [comment]
Here's the desired effect from VSCode with the Solargraph extension installed

![Screenshot from 2019-08-09 17-08-57](https://user-images.githubusercontent.com/1493530/62809257-6d362000-bac8-11e9-9f59-06c9dbc25d56.png)

**Comment by chemzqm** [comment]
Check :CocInfo

**Comment by sethen** [comment]
@chemzqm 

```
## versions

vim version: NVIM v0.4.0-1597-g25fff17d1
node version: v10.16.2
coc.nvim version: 0.0.73-6d4508c366
term: xterm-256color
platform: linux

## Messages
"~/Developer/ruby/something.rb" 0 lines, 0 characters
[coc.nvim] Solargraph is ready.

"something.rb" [Modified] 9 lines --100%--
## Output channel: snippets
```

**Comment by sethen** [comment]
I am using RVM too if that makes a difference, I am not sure why it would though.  The documentation comes up in a floating window when scrolling through the autocompletion list but not for function completion as shown above.

**Comment by sethen** [comment]
Looking at the trace server logs here's what it's coming back with

```
[Trace - 8:12:54 PM] Sending request 'textDocument/signatureHelp - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///home/sethen/Developer/ruby/something.rb"
    },
    "position": {
        "line": 0,
        "character": 9
    }
}


[Trace - 8:12:54 PM] Received response 'textDocument/signatureHelp - (4)' in 1ms.
Result: {
    "signatures": []
}
```

**Comment by chemzqm** [comment]
It's empty, you can try increase timeout for trigger signature help

**Comment by sethen** [comment]
@chemzqm I upped the `signature.triggerSignatureWait` to `300` and still nothing... is this an issue with Solargraph itself?

**Comment by chemzqm** [comment]
Should be, you can see the response is empty. Try upgrade it

**Comment by sethen** [comment]
@chemzqm On the latest release at `0.35.2` and using Ruby `2.6.1`...  Are you able to recreate this or no?
