### ISSUE TITLE
solargraph 0.37.2 changed documentation format, which breaks syntax highlighting

### ISSUE THREAD

**Issue by AlanWarren** [neoclide/coc-solargraph#17]
I recently updated to solargraph 0.37.2, and notice that I lost syntax highlighting in the documentation floating window. 

solargraph used to provide markdown, but now the results are stipped down. Not much is said regarding the change. https://github.com/castwide/solargraph/commit/d633cb2c900ef855230a6bfd5360b3239cb431b4

Are there any other language servers with similar lack of format that coc is able to highlight?
 I wonder if it's possible to convert to markdown in JS. 

Example output 
```json
"documentation": {
        "kind": "markdown",
        "value": "[Kernel#catch](solargraph:/document?query=Kernel%23catch)\n\n

+catch+ executes its block.
 If +throw+ is not called, the block executes\n
normally, and +catch+ returns the value of the last expression evaluated.\n\n 

   catch(1) { 123 } 
           # => 123\n\n

If <code>throw(tag2, val)</code> is called, Ruby searches up its stack for\n
a +catch+ block whose +tag+ has the same +object_id+ as _tag2_. When found,\n
the block stops executing and returns _val_ (or +nil+ if no second argument\n
was given to +throw+).\n\n   

 catch(1) { throw(1, 456) }  # => 456\n   
 catch(1) { throw(1) }       # => nil\n\n
When +tag+ is passed as the first argument, +catch+ yields it as the\n
parameter of the block.\n\n  

  catch(1) {|x| x + 2 }       # => 3\n\n

When no +tag+ is given, +catch+ yields a new unique object (as from\n
+Object.new+) as the block parameter. This object can then be used as the\n
argument to +throw+, and will match the correct +catch+ block.\n\n 

   catch do |obj_A|\n  
   catch do |obj_B|\n    
   throw(obj_B, 123)\n 
      puts \"This puts is not reached\"\n
     end\n\n

    puts \"This puts is displayed\"\n
    456\n
    end\n\n

    # => 456\n\n

    catch do |obj_A|\n 
    catch do |obj_B|\n
        throw(obj_A, 123)\n
        puts \"This puts is still not reached\"\n
      end\n\n

   puts \"Now this puts is also not reached\"\n
    456\n
   end\n\n

    # => 123"
    }
```

**Comment by chemzqm** [comment]
coc.nvim should be able to highlight markdown content, need verbose output from language server.

**Comment by AlanWarren** [comment]
The above snippet is verbose output from the language server.  

**Here's a comparison of solargraph-0.37.1 and 0.37.2 for additional clarity.** 

solargraph 0.37.1 👍 
verbose server log (just the relevant part)
```json
"documentation": {
    "kind": "markdown",
    "value": "[ActiveModel::Validations#errors](solargraph:/document?query=ActiveModel::Validations%23errors)\n\nReturns the `Errors` object that holds all information about attribute error messages.\n\n```\nclass Person\n  include ActiveModel::Validations\n\n  attr_accessor :name\n  validates_presence_of :name\nend\n\nperson = Person.new\nperson.valid? # => false\nperson.errors # => #<ActiveModel::Errors:0x007fe603816640 @messages={name:[\"can't be blank\"]}>\n```"
}
```
screenshot of the floating window generated.
![Screen Shot 2019-09-11 at 11 39 30 AM](https://user-images.githubusercontent.com/294606/64719206-6450b980-d48d-11e9-9a67-d2e4b75d988a.png)


solargraph 0.37.2  👎 
server log - 
```json
"documentation": {
    "kind": "markdown",
    "value": "[ActiveModel::Validations#errors](solargraph:/document?query=ActiveModel::Validations%23errors)\n\nReturns the +Errors+ object that holds all information about attribute\nerror messages.\n\n    class Person\n      include ActiveModel::Validations\n\n    attr_accessor :name\n    validates_presence_of :name\n    end\n\n    person = Person.new\n    person.valid? # => false\n    person.errors # => #<ActiveModel::Errors:0x007fe603816640 @messages={name:[\"can't be blank\"]}>"
}
```
and a screenshot of the floating window generated.
![Screen Shot 2019-09-11 at 12 07 38 PM](https://user-images.githubusercontent.com/294606/64719281-906c3a80-d48d-11e9-8a21-36419fc7f9ce.png)

The basic problem is that solargraph stripped away most of the common markdown format. The code blocks are no longer delimited by triple bactic characters, so vim doesn't understand how to highlight them.  

I'm thinking this may end up being a ticket for solargraph, but I wanted to check with you first.  Can we convert this to markdown ourselves on the client, or is there another way to highlight it?

**Comment by chemzqm** [comment]
We don't have smart code block highlight on vim, so I suggest solargraph fix this by use code block with filetype.

**Comment by AlanWarren** [comment]
Thanks for the info.  I'll open an issue with solargraph.
