### ISSUE TITLE
Failed to start Solargraph after using :cd followed by :e

### ISSUE THREAD

**Issue by davidmathers** [neoclide/coc-solargraph#18]
$ mkdir foo
$ touch foo/bar.rb
$ vim

:e foo/bar.rb

^ Works correctly

:cd foo
:e bar.rb

[coc.nvim] Failed to start Solargraph: /bin/bash: line 0: cd: foo/: No such file or directory

**Comment by davidmathers** [comment]
I should have clarified that vim was closed after the first :e and opened a second time for the :cd & :e.

If vim remains open after solargraph is loaded then it just keeps running with no problem and the :cd & :e work fine.

**Comment by chemzqm** [comment]
No idea, I can't reproduce.

**Comment by davidmathers** [comment]
I tried with different vims and only get the error using macvim.
