### ISSUE TITLE
Pass environment variables

### ISSUE THREAD

**Issue by AprilArcus** [neoclide/coc-solargraph#2]
I'd like a config option to pass environment variables into the solargraph executable, so that I can make a silo for solargraph with `rbenv-gemset`.

**Comment by AprilArcus** [comment]
Thanks for moving so quickly on this! I'm still having trouble getting `coc-solargraph` to work with `rbenv-gemset` and I wonder if you could provide any insight.

Here's my `coc-settings.json`:

![image](https://user-images.githubusercontent.com/2045543/50358031-cf77eb80-050c-11e9-948f-be2df43b843f.png)

And here's my error:

![image](https://user-images.githubusercontent.com/2045543/50358016-c1c26600-050c-11e9-9f9d-74c52073bbc2.png)

![image](https://user-images.githubusercontent.com/2045543/50358101-1239c380-050d-11e9-81d9-5494240e2938.png)

This looks like it's coming from inside `cp.spawn()` to my eye, but I've had trouble debugging it on my local branch; perhaps you have insights.

Do note that when I execute `solargraph` from the command line with the `RBENV_GEMSET` environment variable set, it executes successfully:

![image](https://user-images.githubusercontent.com/2045543/50358271-94c28300-050d-11e9-8ed1-705bdcf06ec7.png)

**Comment by AprilArcus** [comment]
Changing `language-client.ts` line 52 from

`env: configurations.env || process.env`

to

`env: {...process.env, ...configurations.env} || process.env`

fixes the PKG_EXECPATH error for me, but solargraph still can't find its gems:

![image](https://user-images.githubusercontent.com/2045543/50358753-3bf3ea00-050f-11e9-9317-f6291d69b3bb.png)

**Comment by AprilArcus** [comment]
When I set the environment variable directly in the `node` REPL, everything works:

![image](https://user-images.githubusercontent.com/2045543/50358883-aa38ac80-050f-11e9-85d3-43d35f1372cc.png)
![image](https://user-images.githubusercontent.com/2045543/50358889-aefd6080-050f-11e9-885f-08b9b57e19c6.png)

**Comment by chemzqm** [comment]
I think you need to change `commandPath` to full path of solargraph as well.

**Comment by AprilArcus** [comment]
It is, as you can see in the screenshots above.

**Comment by chemzqm** [comment]
I mean `"solargraph.commandPath"` in your coc-settings.json.

**Comment by AprilArcus** [comment]
Yes, I understand. It is set that way. Look at the first screenshot I attached.

**Comment by chemzqm** [comment]
If it still not found the gems, you may need to specify extra env properties.

I hate things like `rbenv`, it's lots of hack of system environment, you need to pass `shell:true` to spawn option to get it's script runned before server start.

**Comment by chemzqm** [comment]
Try latest version 1.0.7

**Comment by AprilArcus** [comment]
Okay, this works (with `commandPath` pointed to `gems/solargraph-0.29.5/bin/solargraph` instead of `bin/solargraph`)

```JSON
{
  "solargraph.commandPath": "/Users/aprilarcus/.rbenv/versions/2.5.3/gemsets/solargraph/gems/solargraph-0.29.5/bin/solargraph",
  "solargraph.env": {
    "RBENV_VERSION": "2.5.3",
    "RBENV_GEMSETS": "solargraph"
  }
}
```

and so does this (with blank `commandPath`)

```JSON
{
  "solargraph.env": {
    "RBENV_VERSION": "2.5.3",
    "RBENV_GEMSETS": "solargraph"
  }
}
```

**Comment by AprilArcus** [comment]
I think you can remove the `shell` option if you want to; it didn't resolve anything for me and I now have a working configuration. It might be useful for `rvm` users, though.

Thank you again for all your help!
