### ISSUE TITLE
Folding not work

### ISSUE THREAD

**Issue by cuongn265** [neoclide/coc-solargraph#20]
Hi, thank you so much for building such an awesome plugin. 

All related functions work perfectly except folding function.

I tried your configuration at https://github.com/neoclide/coc.nvim and use `:Fold` to fold my file but it provided an error message: `[coc.nvim] no range provider found`

I've already installed solargraph and other functions work.

**Comment by chemzqm** [comment]
Your solargraph doesn't have folde support.

**Comment by cuongn265** [comment]
In this repo README I see: `solargraph.folding: Enable folding ranges`. Did I misunderstand something?

**Comment by chemzqm** [comment]
Looks like it's disabled or your solargraph is too old, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by cuongn265** [comment]
Thanks I will have a look

**Comment by praveendhawan** [comment]
@cuongn265 Did you find out what was wrong with the Folding? I am also facing the same issue.

**Comment by cuongn265** [comment]
No I didn't. I have to use other plugin to achieve my goal. My choice: [anyfold](https://github.com/pseewald/vim-anyfold)

**Comment by praveendhawan** [comment]
@chemzqm Can you please open this issue. I checked the logs and I could not find a request being sent to the server to get fold providers. Here are the logs - https://gist.github.com/praveendhawan/06d69669aa3d3ea763de90ccba1fadf4

I did inspect the logs here - https://microsoft.github.io/language-server-protocol/inspector/ and I could not find a request to get folds for the file.
Solargraph Version - 0.38.5
