### ISSUE TITLE
cannot jump to definition inside a class

### ISSUE THREAD

**Issue by leateng** [neoclide/coc-solargraph#22]
inside a class ABC
```ruby
# abc.rb

class ABC
  def initialize
     @a = "hello"
  end

  def a
    @a
  end

  def b
    a
  end
end
```

when cursor on `a` method inside `b`, type `gd`,  can not jump to method `def a`.

but when  in another ruby file,  for example test.rb
```ruby
# test.rb

require './abc'
test = ABC.new
test.a
```
when cursor on method `a`, type `gd`, editor jump to `ABC#a` correctly

**Comment by leateng** [comment]
sorry, this problem caused by my coc config error

**Comment by dvgorod** [comment]
> sorry, this problem caused by my coc config error
> 

How did u fix it?
