### ISSUE TITLE
Keep solargraph running in background

### ISSUE THREAD

**Issue by hibachrach** [neoclide/coc-solargraph#26]
First of all, thank you so much for your plugin! It's truly wonderful.

A question/feature request: would it be possible to maintain the solargraph server after Neovim has quit? I ask because I often launch and quit Neovim many times while programming and the start-up time for solargraph can be quite a while.

**Comment by chemzqm** [comment]
No, it won't work, unless coc.nvim and solargraph support lsif https://github.com/microsoft/lsif-node
