### ISSUE TITLE
Folding is not working

### ISSUE THREAD

**Issue by praveendhawan** [neoclide/coc-solargraph#27]
solargraph supports folding but somehow if we try to get fold ranges, coc-solargraph doesn't send a request to get fold ranges.

https://github.com/castwide/solargraph/issues/291

Logs from solargraph  - https://gist.github.com/praveendhawan/06d69669aa3d3ea763de90ccba1fadf4

**Comment by zachschultz** [comment]
Not working for me either with Solargraph 0.38.6

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by praveendhawan** [comment]
can confirm that its working now. thanks @chemzqm
