### ISSUE TITLE
coc cant start solargraph

### ISSUE THREAD

**Issue by kthibodeaux** [neoclide/coc-solargraph#29]
After updating my system (via `pacman`) and updating my nvim plugins coc-solargraph no longer functions.  I get this error: `[coc.nvim] [NameError] uninitialized constant Solargraph::Parser::VERSION`.

**Comment by chemzqm** [comment]
Should be issue with your language server.

**Comment by kthibodeaux** [comment]
In case anyone ends up here with the same problem, I discovered its cause and created an issue on the solargraph repo: https://github.com/castwide/solargraph/issues/316
