### ISSUE TITLE
How could I use coc-solargraph to lint ruby code via rubocop?

### ISSUE THREAD

**Issue by metalelf0** [neoclide/coc-solargraph#3]
Hi, I'm trying to use this plugin to provide linting via rubocop. I know solargraph should provide linting support via `reporters` (see [here](https://solargraph.org/tips)), but having both a `.rubocop.yml` and a `.solargraph.yml` file in my project root folder don't seem to do the trick. Rubocop is regularly installed and executable. 

Here's my `.solargraph.yml` file, but I think it's not being considered:

```
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
require: []
reporters: 
  - rubocop
domains: []
plugins: []
max_files: 5000
```

Do you have any clue about what is going on? Thanks!

**Comment by dbalatero** [comment]
@metalelf0 I got this working today.

The thing that triggers it seems to be setting:

```json
{
  "solargraph.diagnostics": true
}
```

in your `coc-settings.json` file.

I also set

```json
{
  "solargraph.autoformat": true,
  "solargraph.formatting": true,
  "solargraph.hover": true
}
```

for what it's worth.

<img width="889" alt="Screenshot 2019-04-20 09 47 39" src="https://user-images.githubusercontent.com/59429/56460093-f4149080-6351-11e9-923a-94b15b7425f7.png">

**Comment by dbalatero** [comment]
Oh also make sure you set `"coc.preferences.formatOnSaveFiletypes": ["ruby"]` and then you'll get formatting on save.

My understanding is that coc.nvim will call out to Solargraph for formatting, and Solargraph should respect the Rubocop config and use that to fix.

**Comment by dbalatero** [comment]
FWIW I just reverted to using ALE for linting/autofix as it's just too fast compared to the sync blocking formatOnSave in coc.nvim. I might have mis-configured it though…

@chemzqm Maybe I should be using `:call CocActionAsync('format')` on save with a simple `AutoCmd` hook? But there must be some reason coc.nvim blocks on save format.

There are timing conditions though if you're a fast typer/saver, save once, then save a second change before the autoformat is done.

**Comment by chemzqm** [comment]
Format on save should be sync. 
The server should be fast to calculate TextEdits for format.

**Comment by metalelf0** [comment]
Thank you all! This did the trick! :) We can close the issue, from my perspective. Not sure if you still want to keep it open for sync/async issues.

**Comment by chemzqm** [comment]
It's documented now.
