### ISSUE TITLE
Is there a way to start just one server of solalrgraph

### ISSUE THREAD

**Issue by praveendhawan** [neoclide/coc-solargraph#30]
Let's say I am in the terminal, and in the root directory of the project and I open neovim and open the ruby file to start solargraph. 
Now in another terminal, I go to the same project root directory and open neovim and ruby file which will start another server of solargraph.

Is there a configuration or way to start only one instance of solargraph per project?
If I am in a different project, it should start another instance of solargraph.

Thanks in advance.

**Comment by chemzqm** [comment]
No, lsp don't have support for that
