### ISSUE TITLE
Using the rubocop reporter requires constant "reloading" of file

### ISSUE THREAD

**Issue by thornomad** [neoclide/coc-solargraph#32]
I am not sure how to troubleshoot this and would love some help!

I have `rubocop` set as a solargraph reporter.  I get great linting feedback this way:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/124717/81320491-1e60eb00-9046-11ea-960c-e76789bd3b0f.png">

However, almost constantly (while editing files) see this warning instead: 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/124717/81320452-1143fc00-9046-11ea-8766-22b70c7fbdb0.png">

This happens very regularly while editing.  In order to resolve it, I have to call `:e` to reload the file.  After hitting `:e` the errors go away and the right linting information re-appears.  Shortly after though, the errors come back.

I'm in the habit of constantly hitting `:e<CR>` in my workflow and wondering if there is a better way or something I might investigate with my setup?

Thanks.

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by thornomad** [comment]
@chemzqm - I was trying to get a clean "short" log for you and noticed that this problem does _not_ repeat itself on a clean boot of vim.  Usually I leave vim up for days ... but now that I was trying to reproduce it from start I am not able to.  After a time, something else _is_ happening and that problem begins .. but then if I restart and do the same actions it's not happening.

Anyway, I am going to try and track down a reproduceable case on my end and I will re-open a ticket.  Having this debugging tool is very helpful.  Thank you.
