### ISSUE TITLE
Solargraph Malformed Version Number String

### ISSUE THREAD

**Issue by reedjosh** [neoclide/coc-solargraph#39]
On startup I'm getting 

```[coc.nvim] Failed to start Solargraph: Error: [ArgumentError] Malformed version number string```
 
I'm not sure how to check the startup arguments for Solargraph.

Please help me to troubleshoot this issue.

Thanks!

**Comment by reedjosh** [comment]
So, I removed the lock file, updated Solargraph, rebuilt my bundle environment and a few other things. Now the issue is gone.

I'm not going to close just yet as I would still like advice for troubleshooting this sort of thing in the future, but please do close as you see fit. Thanks again!

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
