### ISSUE TITLE
Update docs to hint about YARD

### ISSUE THREAD

**Issue by dbalatero** [neoclide/coc-solargraph#4]
@chemzqm I didn't realize that Solargraph would do a better job of resolving gem file paths and documentation if you run `yard gems` and configure all future gem installs to generate YARD docs `yard config --gem-install-yri`.

This might be a useful note to include here. Would you be open to a documentation PR?

**Comment by chemzqm** [comment]
PR welcome.

**Comment by chemzqm** [comment]
It's documented now.
