### ISSUE TITLE
Hover not working

### ISSUE THREAD

**Issue by nomasprime** [neoclide/coc-solargraph#44]
- Hover works in NeoVim with coc-tsserver
- Hover works in VSC with Solargraph
- Hover doesn't work in NeoVim with coc-solargraph

See [here](https://github.com/neoclide/coc.nvim/issues/1979#issuecomment-689045311) for more info.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
