### ISSUE TITLE
Format provider not found

### ISSUE THREAD

**Issue by nomasprime** [neoclide/coc-solargraph#46]
Getting this error message in log:

```
2020-10-12T01:39:11.216 WARN (pid:1743) [Handler] - format provider not found!
```

Settings:

```
"solargraph.diagnostics": true,
"solargraph.formatting": true,
"solargraph.autoformat": true
```

**Comment by chemzqm** [comment]
Upgrade your solargraph

**Comment by nomasprime** [comment]
I'm on 0.39.17 [latest].

**Comment by chemzqm** [comment]
You have to enable format by `"solargraph.formatting": true,`

**Comment by nomasprime** [comment]
@chemzqm my mistake, I was accidentally overwriting settings. Apologies for wasting time.

Quick related question, what's this line for in coc.nvim readme and why just typescript and json?

```viml
autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
```

**Comment by chemzqm** [comment]
It's just example since coc-json and coc-tsserver have support for range format.

**Comment by nomasprime** [comment]
@chemzqm assume you mean `textDocument/foldingRange`, thanks.

**Comment by 9enki** [comment]
@nomasprime I have the same situation as you, 
`[coc.nvim]: Error on notification "formatSelected": formatRange provider not found for current buffer, your language server doesn't support it. support it.` 
If you have had any success formatting in ruby files, could you please tell me how to set the formatRange provider?

**Comment by nomasprime** [comment]
Good question…I disabled Solargraph formatting and switched to [coc-diagnostic](https://github.com/iamcco/coc-diagnostic) for all formatting and linting, essentially the LSP equivalent of NeoMake. Actually did this across all language specific LSPs because it's a better solution for consistently configuring these tools.

**Comment by 9enki** [comment]
@nomasprime Thank you for your reply. I switched to coc-diagnostic.

**Comment by nomasprime** [comment]
You're welcome @ikneg 🙂

**Comment by dimanyc** [comment]
@nomasprime cold you share your coc-diagnostic config? I've been trying to get`CocAction('Format')` binding to work with `ruby.rspec` filetype. I'm using [rspec.vim](https://github.com/keith/rspec.vim) for syntax highlighting and it sets `*_spec.rb* filtype to `ruby.rspec` which does not get mapped to solargraph format provider.
