### ISSUE TITLE
using globals

### ISSUE THREAD

**Issue by amirhosseinadev** [neoclide/coc-solargraph#47]
i have installed solargraph gem in global scope but in project scope that uses ruby 3.8, solargraph not installed. how can i make coc.solargraph use global solargraph instead of local solargraph

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-solargraph#configuration-options

**Comment by chemzqm** [comment]
Make sure solargraph is in your $PATH

**Comment by amirhosseinadev** [comment]
thanks this solved my issue
