### ISSUE TITLE
`promptDownload` should disable the update prompt

### ISSUE THREAD

**Issue by smarquez1** [neoclide/coc-solargraph#50]
There should be a way to disable the "Solargraph version xx.xx.xx is available" prompt, in my case I can't update it since I'm using legacy software that uses ruby version 2.3.

<img width="655" alt="Captura de Pantalla 2020-12-18 a la(s) 12 37 10" src="https://user-images.githubusercontent.com/4602587/102632405-d2bf0580-412d-11eb-9e68-68078485d3d8.png">

**Comment by chemzqm** [comment]
`"solargraph.checkGemVersion": false` in your coc-settings.json
