### ISSUE TITLE
coc-fix-current not working

### ISSUE THREAD

**Issue by Haelle** [neoclide/coc-solargraph#51]
NVIM v0.4.3
coc.nvim version: 0.0.79-67cc18bcbf
Ubuntu 18.04
Ruby 2.4.2 

On a line with a lint info, when I run `coc-fix-current` I got the following error : `[coc.nvim] No quickfix action available`.

However when I run `:call CocAction('format')` it fixes everything in the file. 

Do you have any idea how I can get Solargraph fix only one error ?

```json
# coc-settings.json
{
  "coc.preferences.formatOnSaveFiletypes": ["ruby"],
  "solargraph.diagnostics": true
}
```

I also tried adding this, but it doesn't help : 
```json
{
  "solargraph.autoformat": true,
  "solargraph.formatting": true,
  "solargraph.hover": true
}
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
