### ISSUE TITLE
CoC can't find the definition on top level classes

### ISSUE THREAD

**Issue by arashm** [neoclide/coc-solargraph#56]
Having a class definition like this in Rails:

```ruby
module Clients
  module Registrations
    class Request
      def initialize
         ...
      end
      ...
    end
  end
end
```

Imagining I have this line somewhere in the codebase:

```ruby
Clients::Registration::Request.new
```

In VIM, if the cursor is at the beginning of `new`, and try to find the definition, it successfully opens the file at `initialize` method. However if I put the cursor at the beginning of `Request`, it can't find the definition. The same scenario works just fine in Visual Studio Code, successfully opening the file, putting the cursor on the class definition of `Request`.

I'm not sure how CoC works internally, but I feel like it doesn't send the whole `Clients::Registration::Request` to Solargraph and only sends the `Request` part.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by arashm** [comment]
I actually noticed that if I put the cursor on any character other than the first one after `::` it works fine. It's the same in Visual Studio Code. I right click exactly on the first character and press "go to definition", it won't find it.
Indeed seems like an issue with Solargraph.

**Comment by arashm** [comment]
Actually, I think the plugin is sending the request one character off, but it's the same on Visual Studio Plugin which this is based on.
