### ISSUE TITLE
Is it possible to use autocompletion etc when editing files that are not indexed?

### ISSUE THREAD

**Issue by kputnam** [neoclide/coc-solargraph#58]
I have excluded `spec/**` in .solargraph.yml because some files in this directory contain definitions which I don't want to see when editing things in `lib/`. However, now when I edit files in `spec/**`, code completion does not work.

Maybe this happens because the spec files have not been indexed? If so, is there some way to accomplish what I've described -- code completion using definitions from `lib` when editing specs, but when editing `lib`, don't show things defined in `spec`? if that is possible, is there a way to also see definitions in `spec/` (only) when editing files in `spec/`?

I just started using solargraph and coc-solargraph, so please forgive me if this question should be sent to the solargraph repo instead.

**Comment by chemzqm** [comment]
You can make use of vim's builtin completion `:h ins-completion`

**Comment by kputnam** [comment]
Right, but that doesn't use solagraph at all. I want static analysis and all solargraph's intellisense, diagnostics, etc when editing spec files. I just don't want autocomplete to suggest definitions that were loaded from spec files when I'm editing library code.

The best solution I have so far is to create both `.solargraph.yml` and `spec/.solargraph.yml`. The first excludes `spec/**/*.rb` and the second does not exclude those files. It's not ideal because which configuration is used depends on which directory nvim was started in.

It seems like I'm going about this incorrectly, but maybe it's just a limitation of coc-solargraph or solargraph itself.

**Comment by chemzqm** [comment]
Before solargraph provide such settings to support this feature, you can hack the code at https://github.com/neoclide/coc-solargraph/blob/master/src/language-client.ts#L22
