### ISSUE TITLE
Unclear note in the README

### ISSUE THREAD

**Issue by vitaly** [neoclide/coc-solargraph#63]
The following note it unclear:
~~~
Note: solargraph uri solargraph:/ should be solargraph:/// to open with vim.
~~~

What exactly am I supposed to do with this information? why doesn't `coc-solargraph` convert the links to the required format? it already converts html to markdown.

**Comment by vitaly** [comment]
![Screenshot 2021-06-13 at 18 59 22](https://user-images.githubusercontent.com/4193/121816023-8fc39200-cc79-11eb-8f2b-37fd1713b2a5.png)

**Comment by chemzqm** [comment]
Find out it's a bug, `solargraph:/` should work.

**Comment by chemzqm** [comment]
Fixed
