### ISSUE TITLE
Failed to start Solargraph: Required ruby-2.6.6 is not installed.

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc-solargraph#68]
In my macbook, works perfectly, i have a not with linux and shows:

Required ruby-2.6.6 is not installed.
To install do: 'rvm install "ruby-2.6.6"'
/home/yasminvalin/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoun
dException)
        from /home/yasminvalin/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        from /home/yasminvalin/.rbenv/versions/2.6.6/bin/solargraph:23:in `<main>'
        
I switch to nvim_lspconfig to test, and works perfectly, but, i prefer CoC over lspconfig 1000x times.

My .zshrc have the rbenv stuff.
ruby --version returns 2.6.0
solargraph is available on the PATH

**Comment by chemzqm** [comment]
Seems you need configure `"solargraph.commandPath"`

**Comment by otavioschwanck** [comment]
Configured to where is on rbenv (using which solargraph), same results

**Comment by otavioschwanck** [comment]
> Configured to where is on rbenv (using which solargraph), same results

**Comment by otavioschwanck** [comment]
> configured to where is on rbenv (using which solargraph), same results

the strange part is that with nvim_lspconfig works without any tweak.  the solargraph asks
to install ruby 2.6.6 with rvm (that is strange, im using rbenv).  ruby 2.6.6 is installed too.

anything i could do to help you debug this?

**Comment by otavioschwanck** [comment]
For someone that have this issue, here is my solution:

https://github.com/otavioschwanck/mood-nvim#solargraph-asks-to-install-ruby
