### ISSUE TITLE
Remove query from floating window

### ISSUE THREAD

**Issue by micke** [neoclide/coc-solargraph#7]
Hi. Love CoC!
Is there any way to disable the query from showing up in the flaoting window? I think it's unnecessary and in the way.

<img width="793" alt="Screenshot 2019-05-10 at 13 54 49" src="https://user-images.githubusercontent.com/22270/57526255-30258a80-732d-11e9-8fb3-70875da3c382.png">

**Comment by chemzqm** [comment]
There's plan to hide it, https://github.com/neoclide/coc.nvim/issues/611

**Comment by micke** [comment]
@chemzqm thanks! i will close the issue and track the global issue instead.
