### ISSUE TITLE
CocTagFunc not working

### ISSUE THREAD

**Issue by tombell** [neoclide/coc-solargraph#70]
I've set `tagfunc` to be `CocTagFunc` so `ctrl+t` and `ctrl+]` are working when using `coc-tsserver` in JS/TS files. However they don't seem to work in Ruby files when using `coc-solargraph`.

I get the following error:

```
E433: No tags file
E426: tag not found: {The word hovering over}
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
