### ISSUE TITLE
Two instances of solargraph running

### ISSUE THREAD

**Issue by artemave** [neoclide/coc-solargraph#8]
Hello,

There are always two instances of solargraph running, always at ~10% cpu each. Is this normal?

![image](https://user-images.githubusercontent.com/23721/57833161-b45a9080-77b9-11e9-9c77-aa4d5025cc4b.png)

My os is Ubuntu 18.10, coc.nvim and solargraph have been recently updated.

**Comment by chemzqm** [comment]
Checkout `:CocList services` and remove solargraph your have configured.

**Comment by artemave** [comment]
I removed `coc-solargraph` extension and now there is only solargraph process. However, there is obviously no solargraph integration.

As soon as I add the extension back, solargraph starts working, but there are two processes.

`:CocList services` with the extension (2 processes, solargraph integration is working):
![image](https://user-images.githubusercontent.com/23721/57844552-951b2d80-77d0-11e9-8ee6-6c738b758ded.png)

`CocList services` without the extension (1 process, solargraph integration is not working):
![image](https://user-images.githubusercontent.com/23721/57844611-b67c1980-77d0-11e9-96a5-be50dd88c82d.png)

When vim is quit, solargraph process disappears. When vim starts, it only reappears when I open a ruby file.

**Comment by chemzqm** [comment]
solargraph process chould be started by other plugin, ex: ale.

Try your vim with minimal vimrc.

**Comment by artemave** [comment]
You were right - that was ale starting its own solargraph instance. Thanks!
