### ISSUE TITLE
Fix Ruby with rubocop

### ISSUE THREAD

**Issue by sphynx79** [neoclide/coc-solargraph#9]
I want to use command similar to :ALEFix that fix the error in current file.

I set in my coc-setting:
```
  "solargraph.diagnostics": true,
  "solargraph.autoformat": true,
  "solargraph.formatting": true,
  "solargraph.hover": true,
```

this is my .solargraph.yml
```
---
plugins:
- runtime
include:
- "**/*.rb"
exclude:
- .rblcl/**/*
- spec/**/*
- test/**/*
- vendor/**/*
- .git/**/*
- .logs/**/*
require: []
domains: []
reporters:
- rubocop
- require_not_found
plugins: []
max_files: 5000
```
Ho i can fix current buffer ?

**Comment by chemzqm** [comment]
Checkout `:h n_coc-fix-current`.
You have to create your own command if you don't use keymap, checkout https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L282
